/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Analog;

import java.text.NumberFormat;
import java.util.StringTokenizer;
import java.util.Locale;
import javax.swing.JOptionPane;

  
/**
 *
 * @author User
 */
public class Buku extends javax.swing.JFrame {
   //StringTokenizer token;
   //String gantiformat="";
    public String Nama_Buku="";
    public long Harga_Buku;
    public int Jumlah_Beli;
    public long Jumlah_Harga;
    public long Kembalian;
    public long Jumlah_Bayar;
  
    
     /**
     * Creates new form Buku
     */
    public Buku() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        NamaBuku = new javax.swing.JLabel();
        HargaBuku = new javax.swing.JLabel();
        JumlahBeli = new javax.swing.JLabel();
        JumlahHarga = new javax.swing.JLabel();
        JumlahBayar = new javax.swing.JLabel();
        JumlahKembalian = new javax.swing.JLabel();
        IHargaBuku = new javax.swing.JTextField();
        IJumlahBeli = new javax.swing.JTextField();
        IJumlahHarga = new javax.swing.JTextField();
        IJumlahBayar = new javax.swing.JTextField();
        IJumlahKembalian = new javax.swing.JTextField();
        TotalHarga = new javax.swing.JButton();
        IHapus = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        JHitung = new javax.swing.JButton();
        cNamaBuku = new javax.swing.JComboBox<>();
        ICetak = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Toko Buku");

        NamaBuku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaBuku.setText("NAMA BUKU");

        HargaBuku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HargaBuku.setText("HARGA BUKU");

        JumlahBeli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JumlahBeli.setText("JUMLAH BELI");

        JumlahHarga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JumlahHarga.setText("JUMLAH HARGA");

        JumlahBayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JumlahBayar.setText("JUMLAH BAYAR");

        JumlahKembalian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JumlahKembalian.setText("JUMLAH KEMBALIAN");

        IHargaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IHargaBukuActionPerformed(evt);
            }
        });

        IJumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IJumlahBeliActionPerformed(evt);
            }
        });

        IJumlahHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IJumlahHargaActionPerformed(evt);
            }
        });

        IJumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IJumlahBayarActionPerformed(evt);
            }
        });

        IJumlahKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IJumlahKembalianActionPerformed(evt);
            }
        });

        TotalHarga.setText("Total Harga");
        TotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalHargaActionPerformed(evt);
            }
        });

        IHapus.setText("Hapus");
        IHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IHapusActionPerformed(evt);
            }
        });

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        JHitung.setText("Hitung");
        JHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JHitungActionPerformed(evt);
            }
        });

        cNamaBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensiklopedia Sains", "Sejarah Filsafat", "Dapur Nostalgia", "Keajaiban Mimpi", "Sepatu Dahlan", "Surat Dahlan" }));
        cNamaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNamaBukuActionPerformed(evt);
            }
        });

        ICetak.setText("Cetak");
        ICetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICetakActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(NamaBuku, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(HargaBuku, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JumlahBeli, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JumlahHarga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JumlahBayar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JumlahKembalian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IHargaBuku, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IJumlahBeli, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IJumlahHarga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IJumlahBayar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IJumlahKembalian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TotalHarga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IHapus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Keluar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JHitung, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cNamaBuku, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ICetak, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JumlahBeli)
                            .addComponent(HargaBuku)
                            .addComponent(NamaBuku))
                        .addGap(19, 19, 19)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addGap(0, 94, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(IJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(IHargaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(IJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(IJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JHitung))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(IJumlahKembalian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ICetak)
                                        .addGap(116, 116, 116))))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JumlahBayar)
                                .addComponent(JumlahHarga))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(JumlahKembalian)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(TotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Keluar)
                .addGap(56, 56, 56))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaBuku)
                    .addComponent(cNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HargaBuku)
                    .addComponent(IHargaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JumlahBeli)
                    .addComponent(IJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(JHitung)
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JumlahHarga)
                    .addComponent(IJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(TotalHarga)
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IHapus)
                    .addComponent(Keluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JumlahKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IJumlahKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICetak))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IHargaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IHargaBukuActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_IHargaBukuActionPerformed

    private void IJumlahKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IJumlahKembalianActionPerformed
  // TODO add your handling code here:
    }//GEN-LAST:event_IJumlahKembalianActionPerformed

    private void TotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHargaActionPerformed
    //mengonversi tipe data String menjadi integer
    //menampilakn data pada text field dari form
    int Jumlah_Bayar=Integer.parseInt(IJumlahBayar.getText());
    int Jumlah_Harga=Integer.parseInt(IJumlahHarga.getText());
    Kembalian=Jumlah_Bayar-Jumlah_Harga;
    //untuk menampilkan data di kolom jumlah kembalian
    IJumlahKembalian.setText(""+Kembalian);
    // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaActionPerformed

    private void IHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IHapusActionPerformed
    cNamaBuku.setSelectedIndex(-1);
    IHargaBuku.setText("");
    IJumlahBeli.setText("");
    IJumlahHarga.setText("");
    IJumlahBayar.setText("");
    IJumlahKembalian.setText("");
    // TODO add your handling code here:
    }//GEN-LAST:event_IHapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
   //untuk menampilkan dialog informasi
   //null:parameter
    if(JOptionPane.showConfirmDialog(null, " Apakah anda ingin keluar?" , "Yakin", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
   JOptionPane.showMessageDialog(null, " TERIMAKASIH "); 
    //menutup atsu kelusr dari program
   System.exit(0);
   //untuk menutup form
   {this.dispose();
  }
// TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    private void IJumlahHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IJumlahHargaActionPerformed
   
        // TODO add your handling code here:
    }//GEN-LAST:event_IJumlahHargaActionPerformed

    private void IJumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IJumlahBayarActionPerformed
    //
    Jumlah_Bayar=(int) Long.parseLong(IJumlahBayar.getText());
    Kembalian=Jumlah_Bayar-Jumlah_Harga;
    
    // TODO add your handling code here:
    }//GEN-LAST:event_IJumlahBayarActionPerformed

    private void JHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHitungActionPerformed
    //
    //
    Harga_Buku=Integer.parseInt(IHargaBuku.getText());
    Jumlah_Beli=Integer.parseInt(IJumlahBeli.getText());
    Jumlah_Harga=Harga_Buku*Jumlah_Beli;
    //menampilkan data di jumlah harga
    IJumlahHarga.setText(""+Jumlah_Harga);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_JHitungActionPerformed

    private void cNamaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNamaBukuActionPerformed
    //mengembalikan  item atau elemen yang dipiilih
    //menampilkan data di nama buku
    if(cNamaBuku.getSelectedItem().equals("Ensiklopedia Sains")){
        IHargaBuku.setText("279000");
    }else
    if(cNamaBuku.getSelectedItem().equals("Sejarah Filsafat")){
        IHargaBuku.setText("70000");
    }else
    if(cNamaBuku.getSelectedItem().equals("Dapur Nostalgia")){
        IHargaBuku.setText("18000");
    }else
    if(cNamaBuku.getSelectedItem().equals("Keajaiban Mimpi")){
        IHargaBuku.setText("50000");
     }else
    if(cNamaBuku.getSelectedItem().equals("Sepatu Dahlan")){
        IHargaBuku.setText("69000");
     }else
    if(cNamaBuku.getSelectedItem().equals("Surat Dahlan")){
        IHargaBuku.setText("35000");
    }
  
        // TODO add your handling code here:
    }//GEN-LAST:event_cNamaBukuActionPerformed

    private void IJumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IJumlahBeliActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_IJumlahBeliActionPerformed

    private void ICetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICetakActionPerformed
    //menampilkan informasi
    JOptionPane.showMessageDialog(null, "TERIMAKASIH SUDAH MEMBELI        \n Nama Buku     :"+cNamaBuku.getSelectedItem() 
    +"\n Harga Buku     :"+IHargaBuku.getText()+"\n Jumlah Beli     :"+IJumlahBeli.getText() +"\n Jumlah Harga :"+IJumlahHarga.getText()
    +"\n Jumlah Bayar  :"+IJumlahBayar.getText()+"\n Kembalian       :"+IJumlahKembalian.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_ICetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HargaBuku;
    private javax.swing.JButton ICetak;
    private javax.swing.JButton IHapus;
    private javax.swing.JTextField IHargaBuku;
    private javax.swing.JTextField IJumlahBayar;
    private javax.swing.JTextField IJumlahBeli;
    private javax.swing.JTextField IJumlahHarga;
    private javax.swing.JTextField IJumlahKembalian;
    private javax.swing.JButton JHitung;
    private javax.swing.JLabel JumlahBayar;
    private javax.swing.JLabel JumlahBeli;
    private javax.swing.JLabel JumlahHarga;
    private javax.swing.JLabel JumlahKembalian;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel NamaBuku;
    private javax.swing.JButton TotalHarga;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cNamaBuku;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
